### ISSUE TITLE
Hacker Guide / Updating Tracks

### ISSUE THREAD

**Issue by IAmThe2ndHuman** [HackNCState/website#56]
I copied over last year's hacker guide so we can update it with this year's information. The hacker guide is hosted on Notion so if you want to complete this task, please give me the e-mail you use on Notion (or create an account if you don't have one) and I'll give you editing privileges.

This task is for updating the tracks.

[This year's hacker guide](https://hackncstate2025.notion.site/Hack_NCState-2025-Hackerguide-143963046a3880e4a0b2e2b82cd6dca8)
[Last year's for reference](https://amazing-parrot-5b3.notion.site/Hack_NCState-x-Code-Black-Hackerguide-f1982d8ddd7e4c95a07af6a051728120)

**Comment by aaryarajoju** [comment]
my email id on notion - aaryarajoju@gmail.com
